import { ReactNode } from 'react';

import { Header } from '@/content/header';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import { CartProvider } from '../context/CartContext';

const montserratInit = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-montserrat',
});

import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={montserratInit.variable}>
        <CartProvider>
          <Header />

          {children}
        </CartProvider>
      </body>
    </html>
  );
}
